name: anchore
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest      
    - name: run anchore scan
      uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/testimage:latest"
        dockerfile-path: "Dockerfile"
        acs-report-enable: true
    - name: upload anchore scan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
