name: cd
on:
  push:
    branches:
      - master
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/release-please-action@v1.3.2
        with:
          token: ${{ secrets.JEFBOT_PAT }}
          release-type: simple
          package-name: audit-org-keys
