name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: Run Release Please
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      upload-url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup release please
        uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: audit-org-keys
  build-publish:
    name: Build and publish assets
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release-created
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3.1.0
        with:
          go-version: '1.16'
      - name: Setup build cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Build release assets
        run: make dist
      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload-url }}
          asset_path: ./audit-org-keys-windows-amd64.exe
          asset_name: audit-org-keys-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload Linux asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload-url }}
          asset_path: ./audit-org-keys-linux-amd64
          asset_name: audit-org-keys-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload-url }}
          asset_path: ./audit-org-keys-darwin-amd64
          asset_name: audit-org-keys-darwin-amd64
          asset_content_type: application/octet-stream
